server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    auth_basic "Protected Area";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        try_files $uri =404;
    }
}